### ISSUE TITLE
EDIT: Fixes! Plz close

### ISSUE THREAD

**Issue by Drehverschluss** [Nunnery/MythicDrops#231]
FIXED!

**Comment by Drehverschluss** [comment]
Ok i got now Unid items to drop. But what i need to do to only let Mobs drop Unidentified items?

I tryed it together with MythicMobs and put in the drop section "- mythicdrop unidentified" but nothing works. nether "-unidentified mythicdrop".

I settet now 
  item-chance: 1.0
  socket-gem-chance: 0.5
  identity-tome-chance: 0.5
  unidentified-item-chance: 0.9

But i always got 1 normal item too wich is not unidentified.

**Comment by Drehverschluss** [comment]
Allright i got it to work now and i know whats the Problem.

I can only force a Unidentified item to Drop via Mythic Drops. So i could only choose Tables for the standart creature.
Like if i force a trop via PhatsLoot or MythicMobs they just wont drop unidentified. i tryed also to remove the "tierDrops:" for a creature in the "creatureSpawning.yml" But they still drop the item identified.

And fix for this or do i need to life with that till a new version?

**Comment by Drehverschluss** [comment]
I also found a Issue. To help you bit more finding out whats wrong here are some more infos (Like my configs and such).
ust in case. I trop now the items just with MythicDrops, cause it seems Unidentified items are not working though other plugins.

This is my Config
```
version: 4.0.3
options:
  debug: true
  hooking:
    mcmmo: false
  give-mobs-names: false
  give-all-mobs-names: false
  display-mob-equipment: false
  can-mobs-pick-up-equipment: false
  blank-mob-spawn:
    enabled: false
    skeletons-spawn-without-bow: false
multiworld:
  enabled-worlds:
  - world
drops:
  item-chance: 1.0
  socket-gem-chance: 0.2
  custom-item-chance: 0.0     <<<<------ They still drop....Why?
  identity-tome-chance: 0.2
  unidentified-item-chance: 1.0
components:
  creature-spawning-enabled: false
  repairing-enabled: false
  socketting-enabled: true
  identifying-enabled: true
  distance-zones-enabled: false
  populating-enabled: false
display:
  item-display-name-format: '&l%itemtype%'
  tooltip-format:
  - '%baselore%'
  - '&6&l-- SOCKETS --'
  - '%socketlore%'
```
These are my own armor group i made.
```
itemGroups:
  armorGroups:
    CommonHeadsFeather:
    - CUSTOMNPCS_NPCWIZARDHEAD
    - TCONSTRUCT_HELMETWOOD
    - LEATHER_HELMET
    - CUSTOMNPCS_NPCFULLWOODENHEAD
    - CUSTOMNPCS_NPCCOWLEATHERHEAD
```
And the the tier
```
displayName: Common (F)
#displyName is das was neben "Tier: " steht!
displayColor: GREEN
identifierColor: DARK_RED
enchantments:
  safeBaseEnchantments: true
  safeBonusEnchantments: false
  allowHighBaseEnchantments: true
  allowHighBonusEnchantments: true
  baseEnchantments: []
  bonusEnchantments: []
  #- DURABILITY:1:1
  minimumBonusEnchantments: 0
  maximumBonusEnchantments: 0
lore:
  minimumBonusLore: 0
  maximumBonusLore: 2
  baseLore:
  - '&7Tier: %tiername%'
  - '&7Weight: Feather'
  - '%bonuslore%'
  - ''
  - '&6Durability: 300/300'
  - '&7Level: 1'
  - '&8&m-------------------------'
  bonusLore:
  - '&fTest1'
  - '&fTest2'
minimumSockets: 0
maximumSockets: 2
chanceToBeIdentified: 0.9            <<<<--------- What i need to set here to let this tier drop
chanceToHaveSockets: 1.0                              way more than other?
broadcastOnFind: false
itemTypes:
  allowedGroups:
  - CommonHeadsFeather
optimalDistance: -1
maximumDistance: -1
infiniteDurability: false
```
creatureSpawning.yml (That where i define what each Intity can drop right?)
```
version: 4.0.2
spawnPrevention:
  spawnEgg: false
  spawner: true
  custom: false
  above-y:
    world: 255
spawnWithDropChance:
  SKELETON: 1.0
tierDrops:
  SKELETON:
  - commonHeadsFeather
  - commonHeadsLight
  - commonHeadsMedium
  - commonHeadsHeavy
```

And now at the end i become a error all the time. I think i understand it cause it cames up when with this Setting from above a skeleton just dont drop anything (but they should always) than this error comes. http://pastebin.com/K0X03nUt
