### ISSUE TITLE
Socket Gem Enchantments

### ISSUE THREAD

**Issue by jackSHEEP** [Nunnery/MythicDrops#255]
Is it possible to add vanilla enchantments (i.e. Unbreaking or DURABILITY) with the socket gems? I know it's possible to do potion effects, and those are quite easy, but how (if it is possible) could you change it so it adds enchantments of unbreaking, fire aspect, etc.

**Comment by Nunnery** [comment]
It is possible, you just need to do something like the following:
```yaml
socket-gems:
  Harden I:
    type: ARMOR
    enchantments:
    - UNBREAKABLE:5
    weight: 400
    prefix: Hard
    lore:
    - '&4This item brought to you by Nokia.'
```
