### ISSUE TITLE
How to add enchants to a custom item

### ISSUE THREAD

**Issue by kerza4655** [Nunnery/MythicDrops#280]
Anyone know?

**Comment by Nunnery** [comment]
```
socketsword:
  materialName: WOOD_SWORD
  displayName: '&2Socket Sword (Unique)'
  enchantments:
    DAMAGE_ALL: 4
  lore:
  - '&7This sword has sockets!'
  - '&2(Socket)'
  - '&2(Socket)'
  - '&2(Socket)'
  - '&7Find a &2Socket Gem&7 to fill a &2(Socket)'
  spawnOnMonsterWeight: 100
  chanceToDropOnMonsterDeath: 1.0
  broadcastOnFind: true
```
