### ISSUE TITLE
[Question] Socket Gem Effect Length

### ISSUE THREAD

**Issue by Prxmium** [Nunnery/MythicDrops#295]
So I'm wanting to add the withering effect to a sword, and IV is the highest it goes it seems in terms of actually adding the effect when you hit someone with it, but only lasts for three seconds. How would I go about increasing the length that the effect is applied?

Sorry if this is right in front of my face and i'm just missing it.

**Comment by Nunnery** [comment]
To use an example from the default config,

```
  Spikes IV:
    type: ARMOR
    potion-effects:
      WITHER:
        intensity: 0.5
        duration: 2400
        target: OTHER
        radius: 0
        affectsWielder: false
        affectsTarget: false
    weight: 1
    prefix: Heartless
    lore:
    - '&4Withers enemies for 2.0s when hit'
```

That has duration set to 2400, which means 2400 milliseconds, which is 2.4 seconds. You can change that value to anything you want, then divide it by 1000. That's how many seconds long the duration will last.
