### ISSUE TITLE
No enchantments on custom items

### ISSUE THREAD

**Issue by TheRiisager** [Nunnery/MythicDrops#355]
I've tried adding enchantments to my custom items, but none of them have any of the enchantments i've given them. I'm using the latest build of Spigot 1.13 and Mythicdrops.
[customItems.yml.txt](https://github.com/Nunnery/MythicDrops/files/2300908/customItems.yml.txt)

**Comment by Nunnery** [comment]
Try this instead:
```
version: 4.0.3
lorehelmet:
  materialName: GOLDEN_HELMET
  displayName: '&6Epic Helmet of Lore Knowing'
  enchantments:
    BINDING_CURSE: 1
  lore:
  - '&5This bad boy can fit so much lore in it'
  spawnOnMonsterWeight: 100
  chanceToDropOnMonsterDeath: 1.0
  broadcastOnFind: true
wearyboots:
  materialName: LEATHER_BOOTS
  displayName: '&2Boots of a Weary Tower Builder'
  enchantments:
    PROTECTION_FALL:3
  lore:
  - '&7These boots once helped a weary '
  - '&7builder avoid injury from falling'
  spawnOnMonsterWeight: 100
  chanceToDropOnMonsterDeath: 1.0
  broadcastOnFind: true
nukebow:
  materialName: BOW
  displayName: '&4Bow of instant death '
  enchantments:
    ARROW_DAMAGE:5
    ARROW_FIRE:1
    VANISHING_CURSE:1
  lore:
  - '&LIt is said that whoever'
  - '&Lis hit by this bow perishes immediately'
  spawnOnMonsterWeight: 100
  chanceToDropOnMonsterDeath: 1.0
  broadcastOnFind: true
soiledpants:
  materialName: LEATHER_LEGGINGS
  displayName: '&2 Soiled Pants '
  enchantments:
    THORNS:1
  lore:
  - '&9 Pants once worn by someone who'
  - '&9had an... accident...'
  - '&9 They are quite repulsive'
  spawnOnMonsterWeight: 100
  chanceToDropOnMonsterDeath: 1.0
  broadcastOnFind: true
```
